name: Browser Tests

on:
  push:
    branches: [master]
  schedule:
    # Every weekday (Mon-Fri) at 9 in the morning
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  test:
    name: Run browser tests across different operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      BROWSER_TESTS_UID: ${{ secrets.BROWSER_TESTS_UID }}
      BROWSER_TESTS_PWD: ${{ secrets.BROWSER_TESTS_PWD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Run TestCafe tests
        run: yarn browser-test:ci
        with:
          args: 'chrome tests'
